### PR TITLE
Linux->windows cross-compile support

### PR DESCRIPTION
**Pull request by MrPepperoni**

### CODE REVIEW

**Comment by abannerth** [comment]
Just so it's not forgotten, what we found so far:
1. When cross-compiling portaudio we run into a mingw bug caused by the incorrect include guard in `winioctl.h` - should be fixed (preferably not by manually editing the packaged header)
2. `CMAKE_FIND_ROOT_PATH` should contain the location of the cross-compiled dependencies, otherwise our `find_` calls won't look in the right places
   - Make sure to remove the `set(Boost_ROOT ...)` call (that I added in #32) if this is added globally
3. Boost libs are not found without `-DBoost_THREADAPI=win32`

**Comment by abannerth** [comment]
Looks good, but now it has conflicts, pls fix :)

**Comment by MrPepperoni** [comment]
fixed for probably the second to last time :)

**Comment by MrPepperoni** [comment]
pullable once again

**Pull request merged**
